SUPPORTED_LANGUAGES = {"python"}
MAX_SOURCE_CODE_LENGTH = 10_000

MAX_STDOUT_LENGTH = 20_000
MAX_STDERR_LENGTH = 20_000

DEFAULT_EXECUTION_TIMEOUT_SECONDS = 5
DOCKER_MEMORY_LIMIT = "128m"
DOCKER_CPU_LIMIT = "0.5"
PYTHON_DOCKER_IMAGE = "python:3.12-slim"
